name: CI/CD Backend Bank

on:
  push:
    branches: [ "production", "main" ] # Déclenche sur les deux branches

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install flake8 pytest pdoc
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: pytest
      - name: Generate Doc
        env:
            MAIL_USERNAME: "temp"
            MAIL_PASSWORD: "temp"
            MAIL_SERVER: "localhost"
            MAIL_FROM: "temp@temp.com"
            DATABASE_URL: "postgresql://user:pass@localhost/db"
        run: pdoc app routes tests -o documentation 
      - name: Deploy Doc
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add documentation
          git commit -m "Update documentation" || exit 0
          git push

  build-and-push:
    needs: test # Sécurité : Ne build que si les tests passent !
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Indispensable pour pousser sur GHCR
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # On utilise le chemin exact de l'image de djelines
          tags: ghcr.io/djelines/robux_republic/backendbank:latest